
package auk.corp.crmunsubscribe.utilities.alz.aemsoapinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AEMSOAPInterfaceMethodsSoap", targetNamespace = "urn:alz:AEMSOAPInterface")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AEMSOAPInterfaceMethodsSoap {


    /**
     * 
     * @param mId
     * @param pId
     * @param flag
     * @param sessiontoken
     */
    @WebMethod(action = "alz:AEMSOAPInterface#alzUnsub")
    @RequestWrapper(localName = "alzUnsub", targetNamespace = "urn:alz:AEMSOAPInterface", className = "alz.aemsoapinterface.AlzUnsub")
    @ResponseWrapper(localName = "alzUnsubResponse", targetNamespace = "urn:alz:AEMSOAPInterface", className = "alz.aemsoapinterface.AlzUnsubResponse")
    public void alzUnsub(
        @WebParam(name = "sessiontoken", targetNamespace = "urn:alz:AEMSOAPInterface")
        String sessiontoken,
        @WebParam(name = "pId", targetNamespace = "urn:alz:AEMSOAPInterface")
        String pId,
        @WebParam(name = "mId", targetNamespace = "urn:alz:AEMSOAPInterface")
        int mId,
        @WebParam(name = "flag", targetNamespace = "urn:alz:AEMSOAPInterface")
        String flag);

}
