
package auk.corp.crmunsubscribe.xtk.session;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "XtkSession", targetNamespace = "urn:xtk:session", wsdlLocation = "WSDL/logon.schemawsdl.wsdl")
public class XtkSession
    extends Service
{

    private final static URL XTKSESSION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(auk.corp.crmunsubscribe.xtk.session.XtkSession.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = auk.corp.crmunsubscribe.xtk.session.XtkSession.class.getResource(".");
          
            url = new URL(baseUrl, "WSDL/logon.schemawsdl.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/crm/logon.schemawsdl.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        XTKSESSION_WSDL_LOCATION = url;
    }

    public XtkSession(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XtkSession() {
        super(XTKSESSION_WSDL_LOCATION, new QName("urn:xtk:session", "XtkSession"));
    }

    /**
     * 
     * @return
     *     returns SessionMethodsSoap
     */
    @WebEndpoint(name = "sessionMethodsSoap")
    public SessionMethodsSoap getSessionMethodsSoap() {
        return super.getPort(new QName("urn:xtk:session", "sessionMethodsSoap"), SessionMethodsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionMethodsSoap
     */
    @WebEndpoint(name = "sessionMethodsSoap")
    public SessionMethodsSoap getSessionMethodsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:xtk:session", "sessionMethodsSoap"), SessionMethodsSoap.class, features);
    }

}
